// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visma.DataAccess;

namespace Visma.Migrations
{
    [DbContext(typeof(VismaDBContext))]
    [Migration("20220514140254_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Visma.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BossID")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("BossID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            BirthDate = new DateTime(1991, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSalary = 1486.66m,
                            EmploymentDate = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Culver",
                            HomeAddress = "3892 La Follette Drive",
                            LastName = "Carde",
                            Role = "CEO"
                        },
                        new
                        {
                            EmployeeID = 2,
                            BirthDate = new DateTime(1990, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 2006.67m,
                            EmploymentDate = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashton",
                            HomeAddress = "115 Heath Place",
                            LastName = "Early",
                            Role = "Legal"
                        },
                        new
                        {
                            EmployeeID = 3,
                            BirthDate = new DateTime(1995, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 1944.54m,
                            EmploymentDate = new DateTime(2021, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Selma",
                            HomeAddress = "750 Tomscot Parkway",
                            LastName = "Henrionot",
                            Role = "Training"
                        },
                        new
                        {
                            EmployeeID = 4,
                            BirthDate = new DateTime(1985, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 2608.86m,
                            EmploymentDate = new DateTime(2021, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betteanne",
                            HomeAddress = "10636 Marquette Junction",
                            LastName = "Leddie",
                            Role = "Services"
                        },
                        new
                        {
                            EmployeeID = 5,
                            BirthDate = new DateTime(1980, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 2810.83m,
                            EmploymentDate = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Devy",
                            HomeAddress = "65874 Park Meadow Plaza",
                            LastName = "Quilliam",
                            Role = "Human Resources"
                        },
                        new
                        {
                            EmployeeID = 6,
                            BirthDate = new DateTime(1992, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 2,
                            CurrentSalary = 1520.15m,
                            EmploymentDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dollie",
                            HomeAddress = "2 Merry Plaza",
                            LastName = "Whissell",
                            Role = "Services"
                        },
                        new
                        {
                            EmployeeID = 7,
                            BirthDate = new DateTime(1975, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 2,
                            CurrentSalary = 1649.76m,
                            EmploymentDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maude",
                            HomeAddress = "342 Eggendart Place",
                            LastName = "Espinay",
                            Role = "Business Development"
                        },
                        new
                        {
                            EmployeeID = 8,
                            BirthDate = new DateTime(1975, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 5,
                            CurrentSalary = 1499.01m,
                            EmploymentDate = new DateTime(2021, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Garey",
                            HomeAddress = "59 Parkside Lane",
                            LastName = "Maciejak",
                            Role = "Human Resources"
                        },
                        new
                        {
                            EmployeeID = 9,
                            BirthDate = new DateTime(1994, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 2824.65m,
                            EmploymentDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Papagena",
                            HomeAddress = "97 Sugar Plaza",
                            LastName = "Masding",
                            Role = "Business Development"
                        },
                        new
                        {
                            EmployeeID = 10,
                            BirthDate = new DateTime(1971, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 1264.78m,
                            EmploymentDate = new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dedra",
                            HomeAddress = "15 Jenifer Junction",
                            LastName = "Kennham",
                            Role = "Marketing"
                        },
                        new
                        {
                            EmployeeID = 11,
                            BirthDate = new DateTime(1974, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 10,
                            CurrentSalary = 2628.58m,
                            EmploymentDate = new DateTime(2021, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Quintilla",
                            HomeAddress = "5 Blackbird Parkway",
                            LastName = "Rupprecht",
                            Role = "Marketing"
                        },
                        new
                        {
                            EmployeeID = 12,
                            BirthDate = new DateTime(1971, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 3,
                            CurrentSalary = 1903.95m,
                            EmploymentDate = new DateTime(2022, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethel",
                            HomeAddress = "39 Eastwood Junction",
                            LastName = "Ridgwell",
                            Role = "Training"
                        },
                        new
                        {
                            EmployeeID = 13,
                            BirthDate = new DateTime(1993, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 1223.4m,
                            EmploymentDate = new DateTime(2021, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dewey",
                            HomeAddress = "703 Cardinal Street",
                            LastName = "Moorrud",
                            Role = "Engineering"
                        },
                        new
                        {
                            EmployeeID = 14,
                            BirthDate = new DateTime(1994, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 1201.54m,
                            EmploymentDate = new DateTime(2022, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jobi",
                            HomeAddress = "209 Blue Bill Park Way",
                            LastName = "Francecione",
                            Role = "Research and Development"
                        },
                        new
                        {
                            EmployeeID = 15,
                            BirthDate = new DateTime(1973, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 2528.01m,
                            EmploymentDate = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stace",
                            HomeAddress = "0 Hovde Avenue",
                            LastName = "Vassar",
                            Role = "Support"
                        },
                        new
                        {
                            EmployeeID = 16,
                            BirthDate = new DateTime(1987, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 4,
                            CurrentSalary = 2067.06m,
                            EmploymentDate = new DateTime(2022, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fanechka",
                            HomeAddress = "3 Sullivan Drive",
                            LastName = "Cunnington",
                            Role = "Services"
                        },
                        new
                        {
                            EmployeeID = 17,
                            BirthDate = new DateTime(1991, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 5,
                            CurrentSalary = 1825.06m,
                            EmploymentDate = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ogdon",
                            HomeAddress = "6 Mandrake Plaza",
                            LastName = "Micklewicz",
                            Role = "Human Resources"
                        },
                        new
                        {
                            EmployeeID = 18,
                            BirthDate = new DateTime(1989, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 2,
                            CurrentSalary = 1038.53m,
                            EmploymentDate = new DateTime(2021, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gale",
                            HomeAddress = "93782 Green Place",
                            LastName = "Meddows",
                            Role = "Legal"
                        },
                        new
                        {
                            EmployeeID = 19,
                            BirthDate = new DateTime(1977, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 1,
                            CurrentSalary = 1433.01m,
                            EmploymentDate = new DateTime(2022, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Avrom",
                            HomeAddress = "039 Parkside Park",
                            LastName = "Noor",
                            Role = "Sales"
                        },
                        new
                        {
                            EmployeeID = 20,
                            BirthDate = new DateTime(1977, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BossID = 13,
                            CurrentSalary = 1320.31m,
                            EmploymentDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Faulkner",
                            HomeAddress = "43 Grover Parkway",
                            LastName = "Snuggs",
                            Role = "Engineering"
                        });
                });

            modelBuilder.Entity("Visma.Models.ExceptionLog", b =>
                {
                    b.Property<int>("ExceptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("ExceptionID");

                    b.ToTable("ExceptionLog");
                });

            modelBuilder.Entity("Visma.Models.Employee", b =>
                {
                    b.HasOne("Visma.Models.Employee", "Boss")
                        .WithMany()
                        .HasForeignKey("BossID");

                    b.Navigation("Boss");
                });
#pragma warning restore 612, 618
        }
    }
}
